#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.wwy.entity.*
  mapperLocations: classpath:mapper/*.xml

---


#开发配置
spring:
  profiles: dev
  redis:
    database: 0
    host: 192.168.213.133
    port: 6379
    password: yourpassword
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
      timeout: 30000
  datasource:
    url: jdbc:mysql://45.117.101.64:3306/robot
    username: wwy
    password: wwy123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        Log4j2:
          enabled: false
          statementExecutableSqlLogEnable: false
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false