com:
  alipay:
    sofa:
      boot:
        publish-event-to-parent: false
        module-start-up-parallel: true
        allow-bean-definition-overriding: false
        bean-load-cost: 100
#开发配置
server:
  servlet:
    session:
      timeout: 1800

spring:
  session:
    redis:
      namespace: spring:session
      flush-mode: ON_SAVE
    store-type: redis
  application:
    name: demo
  profiles: dev
#  redis:
#    sentinel:
#      master: ESS-INS-SRU_Fz1296Jw_CLUSTER01
#      nodes: 100.80.135.180:8001,100.80.135.181:8001,100.80.135.190:8001
#    password: MvEz0rcGL6xh
#    database: 0
#    timeout: 30000
#    lettuce:
#      pool:
#          # 连接池中的最大空闲连接 默认8
#          max-idle: 8
#          # 连接池中的最小空闲连接 默认0
#          min-idle: 0
#          # 连接池最大连接数 默认8 ，负数表示没有限制
#          max-active: 8
#          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#          max-wait: -1

#    host: 192.168.213.133
#    port: 6379
#    password: yourpassword
#    lettuce:
#      pool:
#        # 连接池中的最大空闲连接 默认8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认0
#        min-idle: 0
#        # 连接池最大连接数 默认8 ，负数表示没有限制
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#        max-wait: -1
